// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/verdex-id/verdex-bot/internal/app/delivery/discord"
	"github.com/verdex-id/verdex-bot/internal/app/delivery/discord/event"
)

// Injectors from injector.go:

func InjectDeliveryDiscord() *delivery.DiscordDelivery {
	discordEventHandler := event.NewDiscordEventHandler()
	discordDelivery := delivery.NewDiscordDelivery(discordEventHandler)
	return discordDelivery
}
